### ISSUE TITLE
no screenshot?

### ISSUE THREAD

**Issue by ctwhome** [lenny1882/vscode-dark-plus-webstorm#3]

**Comment by TheOnlyReadOnly** [comment]
Hope it helps:

![immagine](https://user-images.githubusercontent.com/7527672/59249212-89caee80-8c24-11e9-958b-005826bb8284.png)

**Comment by lenny1882** [comment]
@ctwhome Screenshots added for: CSS, Dart, HTML, JavaScript, JSON, and TypeScript, #7 

@TheOnlyReadOnly Thanks for the screenshot - it too has been added to the README.
