### ISSUE TITLE
CLion support

### ISSUE THREAD

**Issue by pr0grammr** [lenny1882/vscode-dark-plus-webstorm#4]
Do you planning to do a version for CLion? That would be great!

**Comment by lenny1882** [comment]
I wasn't, no, but seeing as how similar all the colouring files for the different JetBrains products are, I may do some sort of builder that programmatically creates one ICLS file from a set of chosen languages.

In the meantime, here's a quick file for CLion (remove the .txt extension). I used the C++ colourings from VSCode as the C colourings were mostly white text (CLion uses the same colourings for both C and C++). Bonus Python colourings are included.

[vscode_dark+_clion.icls.txt](https://github.com/lenny1882/vscode-dark-plus-webstorm/files/3389121/vscode_dark%2B_clion.icls.txt)
