### ISSUE TITLE
parameters not the correct color

### ISSUE THREAD

**Issue by pr0grammr** [lenny1882/vscode-dark-plus-webstorm#5]
I noticed, that the color in the method/function parameters is not correct. 
I updated it myself.. but just for you to know. I am using PhpStorm 2018.3.3

![Bildschirmfoto 2019-03-27 um 12 10 29](https://user-images.githubusercontent.com/17650157/55071607-58ad3a00-5089-11e9-8606-8da0e82ff8a7.png)

**Comment by lenny1882** [comment]
Thanks for the heads-up.

I've done a specific PHPStorm file, using the WebStorm file as a base - more than just the parameter colour was different to how VSCode colours PHP, so you may find you prefer your changes.
