### ISSUE TITLE
the rainbow brackets color is not correct

### ISSUE THREAD

**Issue by aitexiaoy** [lenny1882/vscode-dark-plus-webstorm#6]
the round brackets、square brackets、squiggly brackets color is not corrent

**Comment by lenny1882** [comment]
For which language? I've just compared JavaScript across both VSCode and WebStorm (using the sample code in the WebStorm settings, Editor > Color Scheme > JavaScript) and the brackets match.

If you've also got a code sample that would be helpful.

**Comment by aitexiaoy** [comment]
javascript
